version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/experiment
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          PGHOST: 127.0.0.1
          PGUSER: circleci-demo-ruby
          RAILS_ENV: test
    steps:
      - checkout

      # Restore bundle cache
      - type: cache-restore
        name: Restore bundle cache
        key: rails-demo-bundle-{{ checksum "Gemfile.lock" }}

      - run:
        name: Bundle Install
        command: bundle install --path vendor/bundle

      # Store bundle cache
      - type: cache-restore
        name: Store bundle cache
        key: rails-demo-bundle-{{ checksum 'Gemfile.lock' }}
        paths: vendor/bundle
